apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smsflow-sql-api.fullname" . }}
type: Opaque
stringData:
  appsettings.json: |
    {
      "SqlIntegrationV2": {
        "ConnectionString": {{ .Values.config.connectionString | quote }},
        "PortalMode": {{ .Values.config.portalMode | quote }},
        "PortalBaseUrl": {{ .Values.config.portalBaseUrl | quote }},
        "ApiKey": {{ .Values.config.apiKey | quote }},
        "ChannelType": {{ .Values.config.channelType | quote }},
        "LogDirectory": "/smsflow/logs/worker"
      }
    }
